version: 2
jobs:
  build:
    working_directory: /go/src/github.com/fishworks/gofish
    docker:
      - image: golang:1.11
    environment:
      AZURE_CONTAINER: "releases"
      AZURE_STORAGE_ACCOUNT: "gofish"
    steps:
      - checkout
      - run: echo 'export PATH=/go/src/github.com/fishworks/gofish/bin:$PATH' >> $BASH_ENV
      - run:
          name: install dependencies
          command: .circleci/bootstrap.sh
      - save_cache:
          key: vendor-{{ checksum "Gopkg.toml" }}-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor
      - run:
          name: Build
          command: .circleci/build.sh
      - run:
          name: Test
          command: .circleci/test.sh
      - run:
          name: Deploy to Azure
          command: .circleci/deploy-azure.sh
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
